-- LIKE Operator

SELECT *
FROM employees
WHERE jobTitle LIKE "%Sale%";
-- HERE % REPRESENTS ANY CHARACTER THAT MAY COME BEFORE OR AFTER THE REQUIRED WORD

SELECT *
FROM employees
WHERE firstName LIKE "____y";
-- HERE _ ONLY FILLS 1 CHARACTER DEPENDING ON ITS PLACEMENT